FROM mcr.microsoft.com/mssql/server:2022-latest

COPY entrypoint.sh /usr/init/entrypoint.sh

# Use the entrypoint script as the container's startup command
ENTRYPOINT ["bash", "/usr/init/entrypoint.sh"]