CREATE TABLE public.transactions (
    txcorrelationid                    BIGINT        NOT NULL,
    tenantid                           BIGINT        NOT NULL,
    txgroupcorrelationid               BIGINT        NOT NULL,
    txrefcorrelationid                 BIGINT        NOT NULL,
    walletid                           BIGINT        NOT NULL,
    transactiontypecode                INTEGER       NOT NULL,
    transactionstatuscode              INTEGER       NOT NULL,
    resultcode                         VARCHAR(20)   NOT NULL,
    txadditionaldatajson               TEXT          NOT NULL,
    createddateutc                     TIMESTAMPTZ   NOT NULL,
    updateddateutc                     TIMESTAMPTZ,
    completeddateutc                   TIMESTAMPTZ,
    financialprocesscompleteddateutc   TIMESTAMPTZ,
    isfinancialprocesscompleted        BOOLEAN       NOT NULL,
    towalletid                         BIGINT        NOT NULL,
    txbaseamount                       NUMERIC(18,4),
    txadditionalfee                    NUMERIC(18,4),
    txamountwithadditionalfee          NUMERIC(18,4),
    currencycode                       VARCHAR(10)   NOT NULL,
    txenduserpreviewjson               TEXT          NOT NULL,
    fromdescription                    VARCHAR(500)  NOT NULL,
    todescription                      VARCHAR(500)  NOT NULL,
    kyclevelcode                       VARCHAR(10)   NOT NULL,
    fromaccounttypeid                  VARCHAR(5)    NOT NULL,
    fromaccountid                      BIGINT        NOT NULL,
    fromwalletnumber                   VARCHAR(50)   NOT NULL,
    fromaccountnumber                  VARCHAR(50)   NOT NULL,
    toaccountnumber                    VARCHAR(50)   NOT NULL,
    toaccounttypeid                    VARCHAR(5)    NOT NULL,
    toaccountid                        BIGINT        NOT NULL,
    towalletnumber                     VARCHAR(50)   NOT NULL,
    summarycreateddateutc              TIMESTAMPTZ   NOT NULL,
    isneedsettlement                   BOOLEAN       NOT NULL,
    settlementday                      INTEGER       NOT NULL,
    exttransactionid                   VARCHAR(100),
    channeltype                        VARCHAR(20),
    sourcetype                         VARCHAR(20),
    mediaidentifier                    VARCHAR(50),
    terminalno                         VARCHAR(20),
    mediatype                          VARCHAR(10),
    providerid                         VARCHAR(20),
    toaccounttxbaseamount              NUMERIC(18,4),
    toaccounttxadditionalfee           NUMERIC(18,4),
    toaccounttxamountwithadditionalfee NUMERIC(18,4),
    settlementtypeid                   INTEGER,
    isadjustlimitsuccessprocessed      BOOLEAN,
    isadjustlimitcancelprocessed       BOOLEAN,
    tenantname                         VARCHAR(250),
    tenantcode                         VARCHAR(50),
    ishidden                           BOOLEAN,
    ishiddenforreceiver                BOOLEAN,
    ishiddenforsender                  BOOLEAN,
    fromextaccountnumber               VARCHAR(50),
    toextaccountnumber                 VARCHAR(50),
    fromgroupcode                      VARCHAR(50),
    togroupcode                        VARCHAR(50),
    receiptnumber                      VARCHAR(50)
);
